# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ndrd/Projects/car_detection_final/cosmic_car_detector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ndrd/Projects/car_detection_final/cosmic_car_detector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ndrd/Projects/car_detection_final/cosmic_car_detector/CMakeFiles /home/ndrd/Projects/car_detection_final/cosmic_car_detector/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ndrd/Projects/car_detection_final/cosmic_car_detector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named car-detector

# Build rule for target.
car-detector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 car-detector
.PHONY : car-detector

# fast build rule for target.
car-detector/fast:
	$(MAKE) -f CMakeFiles/car-detector.dir/build.make CMakeFiles/car-detector.dir/build
.PHONY : car-detector/fast

src/car_tracker.o: src/car_tracker.cpp.o
.PHONY : src/car_tracker.o

# target to build an object file
src/car_tracker.cpp.o:
	$(MAKE) -f CMakeFiles/car-detector.dir/build.make CMakeFiles/car-detector.dir/src/car_tracker.cpp.o
.PHONY : src/car_tracker.cpp.o

src/car_tracker.i: src/car_tracker.cpp.i
.PHONY : src/car_tracker.i

# target to preprocess a source file
src/car_tracker.cpp.i:
	$(MAKE) -f CMakeFiles/car-detector.dir/build.make CMakeFiles/car-detector.dir/src/car_tracker.cpp.i
.PHONY : src/car_tracker.cpp.i

src/car_tracker.s: src/car_tracker.cpp.s
.PHONY : src/car_tracker.s

# target to generate assembly for a file
src/car_tracker.cpp.s:
	$(MAKE) -f CMakeFiles/car-detector.dir/build.make CMakeFiles/car-detector.dir/src/car_tracker.cpp.s
.PHONY : src/car_tracker.cpp.s

src/tracker/BlobTracking.o: src/tracker/BlobTracking.cpp.o
.PHONY : src/tracker/BlobTracking.o

# target to build an object file
src/tracker/BlobTracking.cpp.o:
	$(MAKE) -f CMakeFiles/car-detector.dir/build.make CMakeFiles/car-detector.dir/src/tracker/BlobTracking.cpp.o
.PHONY : src/tracker/BlobTracking.cpp.o

src/tracker/BlobTracking.i: src/tracker/BlobTracking.cpp.i
.PHONY : src/tracker/BlobTracking.i

# target to preprocess a source file
src/tracker/BlobTracking.cpp.i:
	$(MAKE) -f CMakeFiles/car-detector.dir/build.make CMakeFiles/car-detector.dir/src/tracker/BlobTracking.cpp.i
.PHONY : src/tracker/BlobTracking.cpp.i

src/tracker/BlobTracking.s: src/tracker/BlobTracking.cpp.s
.PHONY : src/tracker/BlobTracking.s

# target to generate assembly for a file
src/tracker/BlobTracking.cpp.s:
	$(MAKE) -f CMakeFiles/car-detector.dir/build.make CMakeFiles/car-detector.dir/src/tracker/BlobTracking.cpp.s
.PHONY : src/tracker/BlobTracking.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... car-detector"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/car_tracker.o"
	@echo "... src/car_tracker.i"
	@echo "... src/car_tracker.s"
	@echo "... src/tracker/BlobTracking.o"
	@echo "... src/tracker/BlobTracking.i"
	@echo "... src/tracker/BlobTracking.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

