# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ndrd/Projects/motion-tracker-bot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ndrd/Projects/motion-tracker-bot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ndrd/Projects/motion-tracker-bot/CMakeFiles /Users/ndrd/Projects/motion-tracker-bot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ndrd/Projects/motion-tracker-bot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named carTracking

# Build rule for target.
carTracking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 carTracking
.PHONY : carTracking

# fast build rule for target.
carTracking/fast:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/build
.PHONY : carTracking/fast

src/CarTracking.o: src/CarTracking.cpp.o
.PHONY : src/CarTracking.o

# target to build an object file
src/CarTracking.cpp.o:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/CarTracking.cpp.o
.PHONY : src/CarTracking.cpp.o

src/CarTracking.i: src/CarTracking.cpp.i
.PHONY : src/CarTracking.i

# target to preprocess a source file
src/CarTracking.cpp.i:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/CarTracking.cpp.i
.PHONY : src/CarTracking.cpp.i

src/CarTracking.s: src/CarTracking.cpp.s
.PHONY : src/CarTracking.s

# target to generate assembly for a file
src/CarTracking.cpp.s:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/CarTracking.cpp.s
.PHONY : src/CarTracking.cpp.s

src/detector/VehicleCouting.o: src/detector/VehicleCouting.cpp.o
.PHONY : src/detector/VehicleCouting.o

# target to build an object file
src/detector/VehicleCouting.cpp.o:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/detector/VehicleCouting.cpp.o
.PHONY : src/detector/VehicleCouting.cpp.o

src/detector/VehicleCouting.i: src/detector/VehicleCouting.cpp.i
.PHONY : src/detector/VehicleCouting.i

# target to preprocess a source file
src/detector/VehicleCouting.cpp.i:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/detector/VehicleCouting.cpp.i
.PHONY : src/detector/VehicleCouting.cpp.i

src/detector/VehicleCouting.s: src/detector/VehicleCouting.cpp.s
.PHONY : src/detector/VehicleCouting.s

# target to generate assembly for a file
src/detector/VehicleCouting.cpp.s:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/detector/VehicleCouting.cpp.s
.PHONY : src/detector/VehicleCouting.cpp.s

src/motion/MotionTracker.o: src/motion/MotionTracker.cpp.o
.PHONY : src/motion/MotionTracker.o

# target to build an object file
src/motion/MotionTracker.cpp.o:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/motion/MotionTracker.cpp.o
.PHONY : src/motion/MotionTracker.cpp.o

src/motion/MotionTracker.i: src/motion/MotionTracker.cpp.i
.PHONY : src/motion/MotionTracker.i

# target to preprocess a source file
src/motion/MotionTracker.cpp.i:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/motion/MotionTracker.cpp.i
.PHONY : src/motion/MotionTracker.cpp.i

src/motion/MotionTracker.s: src/motion/MotionTracker.cpp.s
.PHONY : src/motion/MotionTracker.s

# target to generate assembly for a file
src/motion/MotionTracker.cpp.s:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/motion/MotionTracker.cpp.s
.PHONY : src/motion/MotionTracker.cpp.s

src/package_bgs/PBAS/PBAS.o: src/package_bgs/PBAS/PBAS.cpp.o
.PHONY : src/package_bgs/PBAS/PBAS.o

# target to build an object file
src/package_bgs/PBAS/PBAS.cpp.o:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/package_bgs/PBAS/PBAS.cpp.o
.PHONY : src/package_bgs/PBAS/PBAS.cpp.o

src/package_bgs/PBAS/PBAS.i: src/package_bgs/PBAS/PBAS.cpp.i
.PHONY : src/package_bgs/PBAS/PBAS.i

# target to preprocess a source file
src/package_bgs/PBAS/PBAS.cpp.i:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/package_bgs/PBAS/PBAS.cpp.i
.PHONY : src/package_bgs/PBAS/PBAS.cpp.i

src/package_bgs/PBAS/PBAS.s: src/package_bgs/PBAS/PBAS.cpp.s
.PHONY : src/package_bgs/PBAS/PBAS.s

# target to generate assembly for a file
src/package_bgs/PBAS/PBAS.cpp.s:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/package_bgs/PBAS/PBAS.cpp.s
.PHONY : src/package_bgs/PBAS/PBAS.cpp.s

src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.o: src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.o
.PHONY : src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.o

# target to build an object file
src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.o:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.o
.PHONY : src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.o

src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.i: src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.i
.PHONY : src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.i

# target to preprocess a source file
src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.i:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.i
.PHONY : src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.i

src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.s: src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.s
.PHONY : src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.s

# target to generate assembly for a file
src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.s:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.s
.PHONY : src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.cpp.s

src/tracker/BlobTracking.o: src/tracker/BlobTracking.cpp.o
.PHONY : src/tracker/BlobTracking.o

# target to build an object file
src/tracker/BlobTracking.cpp.o:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/tracker/BlobTracking.cpp.o
.PHONY : src/tracker/BlobTracking.cpp.o

src/tracker/BlobTracking.i: src/tracker/BlobTracking.cpp.i
.PHONY : src/tracker/BlobTracking.i

# target to preprocess a source file
src/tracker/BlobTracking.cpp.i:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/tracker/BlobTracking.cpp.i
.PHONY : src/tracker/BlobTracking.cpp.i

src/tracker/BlobTracking.s: src/tracker/BlobTracking.cpp.s
.PHONY : src/tracker/BlobTracking.s

# target to generate assembly for a file
src/tracker/BlobTracking.cpp.s:
	$(MAKE) -f CMakeFiles/carTracking.dir/build.make CMakeFiles/carTracking.dir/src/tracker/BlobTracking.cpp.s
.PHONY : src/tracker/BlobTracking.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... carTracking"
	@echo "... src/CarTracking.o"
	@echo "... src/CarTracking.i"
	@echo "... src/CarTracking.s"
	@echo "... src/detector/VehicleCouting.o"
	@echo "... src/detector/VehicleCouting.i"
	@echo "... src/detector/VehicleCouting.s"
	@echo "... src/motion/MotionTracker.o"
	@echo "... src/motion/MotionTracker.i"
	@echo "... src/motion/MotionTracker.s"
	@echo "... src/package_bgs/PBAS/PBAS.o"
	@echo "... src/package_bgs/PBAS/PBAS.i"
	@echo "... src/package_bgs/PBAS/PBAS.s"
	@echo "... src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.o"
	@echo "... src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.i"
	@echo "... src/package_bgs/PBAS/PixelBasedAdaptiveSegmenter.s"
	@echo "... src/tracker/BlobTracking.o"
	@echo "... src/tracker/BlobTracking.i"
	@echo "... src/tracker/BlobTracking.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

